"""update relationships

Revision ID: dc04fb296cbb
Revises: 727023873ad2
Create Date: 2025-09-25 19:14:46.225436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc04fb296cbb'
down_revision: Union[str, Sequence[str], None] = '727023873ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('userid', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'messages', 'users', ['userid'], ['id'])
    op.add_column('private_messages', sa.Column('senderid', sa.Integer(), nullable=False))
    op.add_column('private_messages', sa.Column('recipientid', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'private_messages', 'users', ['senderid'], ['id'])
    op.create_foreign_key(None, 'private_messages', 'users', ['recipientid'], ['id'])
    op.add_column('walls', sa.Column('userid', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'walls', 'users', ['userid'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'walls', type_='foreignkey')
    op.drop_column('walls', 'userid')
    op.drop_constraint(None, 'private_messages', type_='foreignkey')
    op.drop_constraint(None, 'private_messages', type_='foreignkey')
    op.drop_column('private_messages', 'recipientid')
    op.drop_column('private_messages', 'senderid')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'userid')
    # ### end Alembic commands ###
