"""append roles for users

Revision ID: 3ac3110055ec
Revises: 75c55258551e
Create Date: 2025-10-08 19:44:31.079844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac3110055ec'
down_revision: Union[str, Sequence[str], None] = '75c55258551e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    userrole = sa.Enum('admin', 'user', name='role')
    userrole.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', userrole, server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    userrole = sa.Enum('admin', 'user', name='role')
    userrole.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
