from .User import router as users_router
from .Wall import router as walls_router
from .PrivateMessage import router as private_messages_router
from .Message import router as messages_router
from .Friend import router as friends_router
from .File import router as files_router
from .ChatMember import router as chat_members_router
from .Chat import router as chats_router
from .ChannelSubscriber import router as channel_subscribers_router
from .Channel import router as channels_router
